extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  filelog:
    start_at: end
    include:
      - /var/log/auth.log
      - /var/log/kern.log
      - /var/log/syslog
    include_file_path: true
    include_file_name: true
    operators:
      - from: attributes["log.file.name"]
        to: resource["log.file.name"]
        type: move

  otlp:
    protocols:
      grpc:
      http:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
      disk:
      filesystem:
      memory:
        metrics:
          system.memory.utilization:
            enabled: true
      network:
      paging:
      load:

  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
        - targets: ['0.0.0.0:8888']

processors:
  batch:
  resourcedetection:
    detectors: [env, ec2, system]
    system:
      hostname_sources: ["dns","os"]
    timeout: 2s
    override: false

exporters:
  coralogix:
    domain: "cx498.coralogix.com"
    private_key: "cxtp_E8Nr5cLs4jGknrqu5BfnXNazCrB9CP"
    application_name: "Otel-Test-wiser2"
    subsystem_name: "logs"
    application_name_attributes:
      - "applicationName"
    subsystem_name_attributes:
      - "log.file.name"
    timeout: 30s

service:
  pipelines:
    logs:
      receivers: [filelog]
      processors: [resourcedetection, batch]
      exporters: [coralogix]
    metrics:
      receivers: [prometheus, hostmetrics]
      processors: [resourcedetection, batch]
      exporters: [coralogix]

  extensions: [health_check, pprof, zpages]
